# src/mcp_daytona_server/mcp_server.py
import os
from typing import Dict, Optional
from dotenv import load_dotenv
from pydantic_settings import BaseSettings, SettingsConfigDict
from mcp.server.fastmcp import FastMCP, Context
from daytona_sdk import Daytona, CreateWorkspaceParams
from daytona_sdk.daytona import DaytonaConfig

class Settings(BaseSettings):
    """Settings for the FastAPI server."""

    model_config = SettingsConfigDict(
        env_file=".env.local",
        extra="allow"
    )

    mcp_daytona_api_key: str
    mcp_daytona_server_url: str
    mcp_daytona_target: str = "local"

    def __str__(self):
        return f"""
        Daytona Settings:
        API Key: {self.mcp_daytona_api_key[:8]}...
        Server URL: {self.mcp_daytona_server_url}
        Target: {self.mcp_daytona_target}
        """

load_dotenv()
settings = Settings()
print(settings)  # Add this line to print settings

def create_mcp_server() -> FastMCP:
    mcp = FastMCP(name="Daytona MCP", description="MCP Server with Daytona integration.")

    config = DaytonaConfig(
        api_key=settings.mcp_daytona_api_key,
        server_url=settings.mcp_daytona_server_url,
        target=settings.mcp_daytona_target
    )
    print(f"\nDaytona Config: {config}")

    daytona_client = Daytona(config=config)

    @mcp.tool()
    async def create_daytona_env(
        language: str,
        image: Optional[str] = None,
        os_user: Optional[str] = None,
        env_vars: Optional[Dict[str, str]] = None
    ) -> str:
        """Creates a new Daytona development environment. Returns workspace ID."""
        print(f"\nCreating workspace with params:")
        print(f"Language: {language}")
        print(f"Image: {image}")
        print(f"OS User: {os_user}")
        print(f"Env Vars: {env_vars}")

        # Add default values if not provided
        if not image:
            image = "python:3.12"
        if not os_user:
            os_user = ""
        if not env_vars:
            env_vars = {"PYTHONUNBUFFERED": "1"}

        params = CreateWorkspaceParams(
            language=language,
            image=image,
            os_user=os_user,
            env_vars=env_vars
        )
        print(f"\nWorkspace params: {params}")

        try:
            workspace = await daytona_client.create(params)
            print(f"\nCreated workspace: {workspace}")
            print(f"Workspace ID: {workspace.id}")
            print(f"Workspace instance: {workspace.instance}")
            return workspace.id
        except Exception as e:
            print(f"\nError creating workspace: {str(e)}")
            print(f"Error type: {type(e)}")
            raise

    @mcp.tool()
    async def execute_claude_code(
        code: str, workspace_id: str, ctx: Context
    ) -> str:
        """Executes code generated by Claude inside a sandboxed Daytona workspace."""
        workspace = daytona_client.get_current_workspace(workspace_id=workspace_id)
        response = await workspace.process.code_run(code)
        return response.result

    @mcp.tool()
    async def remove_daytona_env(workspace_id: str) -> str:
        """Removes the given Daytona workspace."""
        workspace = daytona_client.get_current_workspace(workspace_id=workspace_id)
        await daytona_client.remove(workspace)
        return "Removed workspace"

    return mcp